# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotifyPreviewApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpotifyPreviewApp
	pod 'OAuthSwift', '~> 2.0.0'
	pod 'SwiftLint'
	pod "PromiseKit", "~> 6.8"
	pod 'KeychainSwift', '~> 19.0'
end
